### ISSUE TITLE
about taskonomy

### ISSUE THREAD

**Issue by menghuaa** [puyiwen/fill_depth_colorization_for_taskonomy#1]
hello, the taskonomy(tiny splits) I downloaded have damaged Pictures. And I try to download it again, but it is the same. Do you download the dataset? Can we communicate for a moment？ My wechat is menghuaaa123. My QQ is 2049304151.

**Comment by puyiwen** [comment]
> 你好，我下载的taskonomy(tiny splits)图片损坏了。我尝试再次下载它，但它是一样的。你下载数据集吗？可以交流一下吗？我的微信是menghuaaa123。我的QQ是2049304151。

Hi, I download the taskonomy_split datasets path is [https://github.com/aim-uofa/AdelaiDepth/blob/main/LeReS/download_data.sh]. Is your download path the same as mine? Howerver there are only corresponding rgb resources in my Baidu cloud disk, and the depth map part is on my laboratory server. .

**Comment by menghuaa** [comment]
> > 你好，我下载的taskonomy(tiny splits)图片损坏了。我尝试再次下载它，但它是一样的。你下载数据集吗？可以交流一下吗？我的微信是menghuaaa123。我的QQ是2049304151。
> 
> Hi, I download the taskonomy_split datasets path is [https://github.com/aim-uofa/AdelaiDepth/blob/main/LeReS/download_data.sh]. Is your download path the same as mine? Howerver there are only corresponding rgb resources in my Baidu cloud disk, and the depth map part is on my laboratory server. .

I currently only need the rgb resources. And I didn't use this download path. I use this https://datasets.epfl.ch/taskonomy/links.txt

**Comment by puyiwen** [comment]
> > > 你好，我下载的taskonomy(tiny splits)图片损坏了。我尝试再次下载它，但它是一样的。你下载数据集吗？可以交流一下吗？我的微信是menghuaaa123。我的QQ是2049304151。
> > 
> > 
> > Hi, I download the taskonomy_split datasets path is [https://github.com/aim-uofa/AdelaiDepth/blob/main/LeReS/download_data.sh]. Is your download path the same as mine? Howerver there are only corresponding rgb resources in my Baidu cloud disk, and the depth map part is on my laboratory server. .
> 
> I currently only need the rgb resources. And I didn't use this download path. I use this https://datasets.epfl.ch/taskonomy/links.txt

If you don't use this path, the taskonomy we downloaded may not be the same. I also downloaded it according to your download link, but my network is unstable, and the download part is broken, so I chose the taskonomy data summarized by the rest of github. I compared the amount of data downloaded from my link and the taskonomy tiny link. The amount of data downloaded from taskonomy tiny is more than what I downloaded. The data I downloaded has a total of more than 130,000 pieces. It is probably a part of the data distribution extracted from each scene.
